- packageId: mbc_pws_sensor_cos
    packageType: COSPackage
    packageManifestParams:
      objectType: loadsensing_tiltmeter
      title: mbc_pws_sensor_cos
      position: left
      popupWidth: 440
      popupHeight: 335
