logger:
  level: <%= ENV['LOG_LEVEL'] %>
  stdout: true
  to_file: false

database:
  database: <%= ENV['DB_NAME'] %>
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  user: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

redis:
  url: <%= ENV['REDIS_URL'] %>

flask_debug_mode: <%= ENV['API_DEBUG_MODE'] %>

external_alerts_module: <%= ENV['EXTERNAL_ALERTS_MODULE'] %>
response_plans_api: <%= ENV['RESPONSE_PLANS_API'] %>
responder_api: <%= ENV['RESPONDER_API'] %>
